@echo off

mkdir build > nul
pushd build

set COMMON_COMPILE_FLAGS=/nologo /Gr /GR- /GS- /GF /Gy /fp:fast /fp:except- /EHa- /EHc- /EHs- /std:c++latest /diagnostics:caret /MP /utf-8 /W4 /WX
set COMMON_DEFINES=/UUNICODE /U_UNICODE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /DWIN32_LEAN_AND_MEAN /DNOMINMAX /DVC_EXTRALEAN
set COMMON_LINK_FLAGS=/OPT:REF /OPT:ICF /INCREMENTAL:NO /SUBSYSTEM:WINDOWS
set COMMON_DISABLED_WARNINGS=/wd4100 /wd4189 /wd4702 /wd4805 /wd4127
set COMMON_LINK_LIBRARIES=user32.lib gdi32.lib

set DEBUG_COMPILE_FLAGS=/Od /Zi
set DEBUG_DEFINES=/DE_DEBUG_BUILD
set DEBUG_LINK_FLAGS=/DEBUG

cl ../src/win32_entrypoint.cpp %COMMON_COMPILE_FLAGS% %DEBUG_COMPILE_FLAGS% %COMMON_DISABLED_WARNINGS% /Fe:battlecity_debug.exe %COMMON_DEFINES% %DEBUG_DEFINES% /link %COMMON_LINK_FLAGS% %DEBUG_LINK_FLAGS% %COMMON_LINK_LIBRARIES%

popd