@ECHO OFF

MKDIR build > nul
PUSHD build
@REM /Gs99999999 /guard:cf-
SET COMMON_COMPILE_FLAGS=/nologo /Gr /GR- /GS- /GF /Gy /fp:fast /fp:except- /EHa- /EHc- /EHs- /std:c++latest /diagnostics:caret /MP /utf-8 /W4 /WX
SET COMMON_DEFINES=/UUNICODE /U_UNICODE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /DWIN32_LEAN_AND_MEAN /DNOMINMAX /DVC_EXTRALEAN
SET COMMON_LINK_FLAGS=/OPT:REF /OPT:ICF /INCREMENTAL:NO
SET COMMON_DISABLED_WARNINGS=/wd4100 /wd4189 /wd4702 /wd4805 /wd4127 /wd4700 /wd4201 /wd4530
SET COMMON_LINK_LIBRARIES=user32.lib gdi32.lib

SET DEBUG_COMPILE_FLAGS=/Od /Zi
SET DEBUG_DEFINES=/DE_DEBUG_BUILD
SET DEBUG_LINK_FLAGS=/DEBUG /SUBSYSTEM:CONSOLE

cl ../src/win32_entrypoint.cpp %COMMON_COMPILE_FLAGS% %DEBUG_COMPILE_FLAGS% %COMMON_DISABLED_WARNINGS% /Fe:battlecity_debug.exe %COMMON_DEFINES% %DEBUG_DEFINES% /link %COMMON_LINK_FLAGS% %DEBUG_LINK_FLAGS% %COMMON_LINK_LIBRARIES%

MKDIR shaders > nul
COPY "..\src\shaders" "shaders" /Y

POPD